# Generated by Django 4.1.6 on 2023-02-08 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_alter_attendance_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="TgStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tg_username",
                    models.CharField(max_length=254, verbose_name="Логин в телеграмм"),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram",
                        to="attendance.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь студента с телеграмм логином",
                "ordering": ("tg_username",),
            },
        ),
    ]
