# Generated by Django 4.0 on 2023-02-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_tgstudent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tgstudent',
            options={'ordering': ('tg_username',), 'verbose_name': 'Связь студента с телеграмм логином', 'verbose_name_plural': 'Связи студента с телеграмм логином'},
        ),
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='attendance.Course'),
        ),
    ]
